jojo_layout/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import index

app_name='jojo_layout'

urlpatterns = [
    url(r'^$', index, name='jojo_layout'),
]

jojo_style/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import index

app_name='jojo_style'

urlpatterns = [
    url(r'^$', index, name='jojo_style'),
]

jojodoc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import jojo_layout.urls as index
from jojo_layout.views import index as layout
from jojo_style.views import index as style
from jojo_component.views import index as component

app_name='jojodoc'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include(index, namespace='index')),
    url(r'^layout', layout, name='layout'),
    url(r'^style', style, name='style'),
    url(r'^component', component, name='component'),
]

jojo_component/models.py
from django.db import models

# Create your models here.

jojo_style/models.py
from django.db import models

# Create your models here.

baseapp/views.py
from django.shortcuts import render

# Create your views here.

jojo_component/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'jojo_component/base.html')

jojo_layout/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'jojo_layout/base.html')

jojo_style/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'jojo_style/base.html')

baseapp/templates/layout/base.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE HTML>
<html lang=en>

<head>
    <meta charset="utf-8">
    <title>Jojonomic Pro</title>
    <!-- Meta Data here -->
    <meta name="theme-color" content="#2196F3">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    
    <!-- Links -->
    <!-- TODO ganti link bs -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/lib/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link type="image/x-icon" rel="shortcut icon" href="{% static 'img/favicon-96x96.png' %}" />
    <link type="image/png" rel="shortcut icon" href="{% static 'img/favicon-16x16.png' %}" />
    <!-- <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">     -->
    
    <!-- Style -->
    <!-- <link type="text/css" rel="stylesheet" href="{% static 'css/lib/bootstrap.min.css' %}" media="screen,projection"/>     -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/style_pisah.css' %}" media="screen,projection"/>    
    <!-- <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" media="screen,projection" /> -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/style_general.css' %}" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/style_navbar.css' %}" media="screen,projection" />
    <!-- <link type="text/css" rel="stylesheet" href="{% static 'css/style_sidebar.css' %}" media="screen,projection" /> -->
    <!-- <link type="text/css" rel="stylesheet" href="{% static 'css/style_screen.css' %}" media="screen,projection" /> -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/style_example.css' %}" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/index.bundle.css' %}" media="screen,projection" />
    
    <!-- style grid -->
        <link type="text/css" rel="stylesheet" href="{% static 'css/grid/grid.css' %}" media="screen,projection" />
    <link rel="stylesheet" media="(min-width: 768px) and (max-width:1049px)" href="{% static 'css/grid/grid-sm.css' %}">
    <link rel="stylesheet" media="(min-width: 1050px) and (max-width:1439px)" href="{% static 'css/grid/grid-md.css' %}">
    <link rel="stylesheet" media="(min-width: 1440px)" href="{% static 'css/grid/grid-lg.css' %}">
    {% block css %}
    {% endblock %}

    <!-- Script -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js" integrity="sha256-8WqyJLuWKRBVhxXIL1jBDD7SDxU936oZkCnxQbWwJVw=" crossorigin="anonymous"></script>    
    <!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> -->
   
    <!-- Scrollbar Custom -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/lib/scrollbar-style/style.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/lib/scrollbar-style/prettify/prettify.css' %}" />
    <script src="{% static 'css/lib/scrollbar-style/prettify/prettify.js' %}"></script>
    <script src="{% static 'css/lib/scrollbar-style/jquery.scrollbar.js' %}"></script>
    <script>
        jQuery(document).ready(function(){
            jQuery('.scrollbar-macosx').scrollbar();
        });
    </script>
    


</head>
<body >
<!-- Header Line -->
<div class="header-shadow"></div>
<div id="header1"></div>
<div id="header2"></div>
<div id="header3"></div>
<div id="header4"></div>
<div id="header5"></div>

<!--Menu Data-->
<div id="wrapper" class="wrapper">

    {% include 'partials/navbar.html' %}
    {% include 'partials/sidebar.html' %}

    <!-- Content -->
    <div id="page-content-wrapper">
        {% block content %}
        {% endblock %}
    </div>
</div>

{% block jsend %}
{% endblock %}
</body>

</html>

</head>

baseapp/templates/partials/navbar.html
<div id="navbar-wrapper">
	<nav class="navbar navbar-fixed-top">
		<div class="navbar-header">
			GUIDELINE DASHBOARD
		</div>
		<ul class="nav navbar-nav navbar-right">
			<li class="nav-item"><span><i class="fa fa-credit-card-alt fa-green" aria-hidden="true"></i></span></li>
			<li class="divider nav-item"></li>
			<li class="nav-item"><span><i class="fa fa-th fa-orange" aria-hidden="true"></i></span></li>
			<li class="nav-item"><i class="fa fa-envelope fa-purple" aria-hidden="true"></i></li>
			<li class="nav-item"><i class="fa fa-cog fa-blue" aria-hidden="true"></i></li>
			<li class="divider nav-item"></li>
			<li class="nav-dropdown">
				<button class="nav-dropbtn">
					<i class="fa fa-user-circle-o" aria-hidden="true"></i>
					<span class="user">John Smith</span> 
					<i class="fa fa-chevron-down" aria-hidden="true"></i>
				</button>
				<div class="dropdown-content">
					<a href="#">Link 1</a>
					<a href="#">Link 2</a>
					<a href="#">Link 3</a>
				</div>
			</li>
		</ul>
	</nav>
</div>
<!-- /navbar -->

baseapp/templates/partials/sidebar.html
{% load static %}
{% load staticfiles %}


    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar sidebar-nav sidebar-fixed-left">
            <li class="sidebar-brand">
                <a href="{% url 'index:jojo_layout' %}"></a>
            </li>
            <li class="sidebar-item" id="sidebar-item-summary">
                <a href="#">
                    <span><i class="fa fa-th-large" aria-hidden="true"></i></span>
                    <span class="sidebar-item-text">Summary</span>
                </a>
            </li>
            <li class="sidebar-item" id="sidebar-item-layout">
                <a href="{% url 'layout' %}">
                    <span><i class="fa fa-object-group" aria-hidden="true"></i></span>
                    <span class="sidebar-item-text">Layout</span>
                </a>
            </li>
            <li class="sidebar-item" id="sidebar-item-style">
                <a href="{% url 'style' %}">
                    <span><i class="fa fa-paint-brush" aria-hidden="true"></i></span>
                    <span class="sidebar-item-text">Style</span>    
                </a>
            </li>
            <li class="sidebar-item" id="sidebar-item-component">
                <a href="{% url 'component' %}">
                    <span><i class="fa fa-columns" aria-hidden="true"></i></span>
                    <span class="sidebar-item-text">Component</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->

jojo_component/templates/jojo_component/base.html
{% extends 'layout/base.html' %}
{% load static %}
{% load staticfiles %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/jojo_component/style.css' %}" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/style_component.css' %}" media="screen,projection" />
{% endblock %}

{% block content %}

<div class="container">
    {% include 'jojo_component/partials/button.html' %}
    {% include 'jojo_component/partials/input.html' %}
    {% include 'jojo_component/partials/flow.html' %}
    {% include 'jojo_component/partials/summaryblock.html' %}
</div>
{% endblock %}

{% block jsend %}
<script src="{% static 'js/component.js' %}"></script>
{% endblock %}

jojo_component/templates/jojo_component/partials/button.html
<section>
    <div class="title">
        <i class="fa fa-play-circle" aria-hidden="true"></i>
        <h4 style="display:inline-block">Button</h4>
    </div>
    <div class="content">
            All Button using fontsize 14px, line space 20px , padding left & right 25px,  padding Bottom & Top 7px. 
    </div>
    <div class="row" style="padding-left:10px;">
        <div class="col-1"></div>
        <div class="col-sm-2 col-md-2 col-lg-2"><b>Default</b></div>
        <div class="col-sm-2 col-md-2 col-lg-2"><b>Hover</b></div>
        <div class="col-sm-2 col-md-2 col-lg-2"><b>Active</b></div>
        <div class="col-sm-2 col-md-2 col-lg-2"><b>Disabled</b></div>
    </div>
    <div class="row">
        <div class="col-1"><b>Primary</b></div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--blue">Button</div>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--blue">Button</div>                
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--blue" style="background-color:#28708E">Button</div>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--blue btn--disabled">Button</div>
        </div>
    </div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--black">Button</div>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--black">Button</div>                
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--black">Button</div>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--black btn--disabled">Button</div>
        </div>
    </div>
    <div class="row wrapper-reverse">
        <div class="col-1"></div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--reverse">Button</div>   
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--reverse">Button</div>                
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--reverse" style="background-color:#E2E2E2">Button</div>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--primary btn--primary--reverse btn--disabled">Button</div>
        </div>
    </div>
    <div class="row">
            <div class="col-1"><b>Secondary</b></div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <div class="btn btn--secondary">Button</div>   
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <div class="btn btn--secondary">Button</div>                
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <div class="btn btn--secondary" style="color:#28708E">Button</div>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <div class="btn btn--secondary btn--disabled">Button</div>
            </div>
        </div>
    <div class="row wrapper-reverse">
        <div class="col-1"></div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--secondary--reverse">Button</div>   
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--secondary--reverse">Button</div>                
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--secondary--reverse" style="color:#E2E2E2">Button</div>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <div class="btn btn--secondary--reverse btn--disabled">Button</div>
        </div>
    </div>
</section>

jojo_component/templates/jojo_component/partials/input.html
<section>
    <div class="title">
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
        <h4 style="display:inline-block">Input Field</h4>    
    </div>
    <div>
        All fields should be shown with a label.<br /> 
        Both the label, placeholder and border has the colour #E2E2E2 . <br />
        Other colours can be found in the sceme. <br />
    </div>
    <div>
        <form>
            <div class="row">
                <div class="form-group col-md-6 col-sm-6">
                    <label>Label</label>
                    <input type="text" class="form-control" placeholder="Placeholder">
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <label id="disabled">Disabled</label>
                    <input type="text" class="form-control" placeholder="Placeholder" disabled>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6 col-sm-6">
                    <label id="label-active">Active</label>
                    <input id="input-active" type="text" class="form-control" placeholder="Placeholder">
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <label id="label-invalid">Wrong Input</label>
                    <input id="input-invalid" type="text" class="form-control" placeholder="Placeholder">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <label>Time Picker</label>
                    <div class="input-group">
                        <input type="time" class="form-control" placeholder="Placeholder" id="bg-time-right">
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <label>Dropdown</label>
                    <select class="custom-select" id="bg-chevrondown-right">
                        <option selected>Choose...</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <label>Date Picker</label>
                    <div class="input-group">
                        <input type="date" class="form-control" placeholder="Placeholder" id="bg-date-right">
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <label>With Icon</label>
                    <div class="input-group">
                        <input type="Input" id="bg-user-left" class="form-control" placeholder="Placeholder">
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <label>Text Area</label>
                    <div class="input-group">
                        <textarea rows="3" class="form-control" placeholder="Placeholder"></textarea>
                    </div>
                </div>
            </div>
            <div class="example">
                <div class="example-unit">
                    <div class="checkbox-item">
                        <div class="check">
                            <input type="checkbox" name="checkbox_name" id="checkbox_id_1" value="1">
                            <label for="checkbox_id_1">
                                <span></span>
                                Unchecked
                            </label>    
                        </div>
                        <!-- <span class="checkbox-item-label">Checkbox</span> -->
                    </div>
                    <div class="checkbox-item">
                        <div class="check">
                            <input type="checkbox" name="checkbox_name" id="checkbox_id_2" value="1" checked>
                            <label for="checkbox_id_2">
                                <span></span>
                                Checked
                            </label>    
                        </div>
                        <!-- <span class="checkbox-item-label">Checkbox</span> -->
                    </div> 
                </div>
                <div class="example-unit">
                    <div class="radio-item">
                        <input type="radio" name="radio_name" id="radio-id-1" value="1">
                        <label for="radio-id-1" class="radio-button-label">
                            Uncheck
                        </label>    
                    </div>
                    <div class="radio-item">
                        <input type="radio" name="radio_name" id="radio-id-2" value="2" checked>
                        <label for="radio-id-2" class="radio-button-label">
                            Check
                        </label>
                    </div> 
                </div>
                <div class="example-unit">
                    <div style="padding-bottom:10px;">Toggle Button</div>
                    <div>
                        <span style="padding-right:10px;">Off</span>
                        <div class="checkbox checkbox-slider--b-flat checkbox-slider-jojoblue" style="display:inline-block;">
                            <label>
                                <input type="checkbox" id="toggle-id" name="toggle_name">
                                <span></span>
                            </label>
                        </div>
                        <span style="padding-left:10px;">On</span>
                    </div>
                </div>            
            </div>
        </form>    
    </div>
</section>

jojo_layout/templates/jojo_layout/base.html
{% extends 'layout/base.html' %}
{% load static %}
{% load staticfiles %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/jojo_layout/jojo_layout.css' %}" media="screen,projection" />
{% endblock %}
{% block content %}

<div class="container">
    <div class="title">
        <span><i class="fa fa-desktop" aria-hidden="true"></i></span> 
        <h4 style="display: inline-block;">Display</h4>
    </div>
    <div class="content">
        The display helpers allow you to control the display of content. This includes being conditionally visible based upon the current viewport, 
        or the actual element display type.
    </div>
    <div class="content"s>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Device</th>
                <th scope="col">Code</th>
                <th scope="col">Type</th>
                <th scope="col">Range</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                    <span><i class="fa fa-mobile" aria-hidden="true"></i></span> 
                    Small
                </td>
                <td><b>sm</b></td>
                <td>Tablet</td>
                <td>768px - 1049px</td>
              </tr>
              <tr>
                <td>
                    <span><i class="fa fa-laptop" aria-hidden="true"></i></span> 
                    Medium
                </td>
                <td><b>md</b></td>
                <td>Laptop</td>
                <td>1050px - 1439px</td>
              </tr>
              <tr>
                <td>
                    <span><i class="fa fa-desktop" aria-hidden="true"></i></span>
                    Large
                </td>
                <td><b>lg</b></td>
                <td>Desktop</td>
                <td>1440px ></td>
              </tr>
            </tbody>
          </table>
    </div>
    <div class="title">
        <span><i class="fa fa-sort-amount-asc" aria-hidden="true"></i></span>
        <h4 style="display: inline-block;"> GRID & BREAK POINTS</h4>
    </div>
    <div class="content">
            Dashboard Container from navigation bar and will using 12 Grid Column and Gutter 15px.
    </div>
</div>

<div id="layout-preview">
    <div class="row">
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
        </div>
    </div>
</div>

{% endblock %}

jojo_style/templates/jojo_style/base.html
{% extends 'layout/base.html' %}
{% load static %}
{% load staticfiles 
{% block css %}
<link type="text/css" rel="stylesheet" href="{% static 'css/jojo_style/jojo_style.css' %}" media="screen,projection" />
{% endblock %}

{% block content %}
<div class="container">
    {% include 'jojo_style/partials/style_color.html' %}

    {% include 'jojo_style/partials/style_icon.html' %}

    {% include 'jojo_style/partials/style_typography.html' %}
</div>
{% endblock %}

jojo_style/templates/jojo_style/partials/style_color.html
<div class="title">
    <span><i class="fa fa-tint" aria-hidden="true"></i></span>
    <h4 style="display:inline-block">Color Pallete</h4>
</div>
<div class="content">
    <b>
        PRIMARY CONTENT COLOR
    </b>
</div>
<div class="color_example">
    <div class="card">
        <div class="card__content bgcolor--blue"></div>
        <div class="card__description">
            <h4>#42A5CE</h4>
            <div class="content">Blue</div>
        </div>
    </div>
    <div class="card">
        <div class="card__content bgcolor--black"></div>
        <div class="card__description">
            <h4>#333133</h4>
            <div class="content">Black</div>
        </div>
    </div>
    <div class="card">
        <div class="card__content bgcolor--grey"></div>
        <div class="card__description">
            <h4>#E2E2E2</h4>
            <div class="content">Grey</div>
        </div>
    </div>
    <div class="card">
        <div class="card__content bgcolor--white"></div>
        <div class="card__description">
            <h4>#FFFFFF</h4>
            <div class="content">White</div>
        </div>
    </div>
</div>
<div class="content">
    <b>
        SECONDARY CONTENT COLOR
    </b>
</div>
<div class="color_example">
    <div class="card">
        <div class="card__content bgcolor--darkblue"></div>
        <div class="card__description">
            <h4>#28708e</h4>
            <div class="content">Dark Blue</div>
        </div>
    </div>
    <div class="card">
        <div class="card__content bgcolor--boldblack"></div>
        <div class="card__description">
            <h4>#000000</h4>
            <div class="content">Bold Black</div>
        </div>
    </div>
    <div class="card">
        <div class="card__content bgcolor--darkgrey"></div>
        <div class="card__description">
            <h4>#808285</h4>
            <div class="content">Dark Grey</div>
        </div>
    </div>
</div>
<div class="color_example">
    <div class="card">
        <div class="card__content bgcolor--green"></div>
        <div class="card__description">
            <h4>#4DB356</h4>
            <div class="content">Green</div>
        </div>
    </div>
    <div class="card">
        <div class="card__content bgcolor--red"></div>
        <div class="card__description">
            <h4>#D2232B</h4>
            <div class="content">Red</div>
        </div>
    </div>
    <div class="card">
        <div class="card__content bgcolor--orange"></div>
        <div class="card__description">
            <h4>#F89B24</h4>
            <div class="content">Orange</div>
        </div>
    </div>
    <div class="card">
        <div class="card__content bgcolor--yellow"></div>
        <div class="card__description">
            <h4>#FFEB3B</h4>
            <div class="content">Yellow</div>
        </div>
    </div>
    <div class="card">
        <div class="card__content bgcolor--purple"></div>
        <div class="card__description">
            <h4>#890C4F</h4>
            <div class="content">Purple</div>
        </div>
    </div>
</div>

jojo_style/templates/jojo_style/partials/style_icon.html
<div class="title">
    <span><i class="fa fa-glass" aria-hidden="true"></i></span>
    <h4 style="display:inline-block">Icon</h4>
</div>
<div class="content">
    The icons are from “<b>FontAwesome</b>” ver 4.7.0 and can be downloaded from fontawesome.io You can get the icons in SVG, PNG, font-format or embed class per icon. They are licensed under CCBY and are free to use.
    <br />
    <br />
    Link:
    <a href="http://fontawesome.io/icons/" target="_blank">http://fontawesome.io/icons/</a>
    <br />
    <br />
    <div>
        <span><i class="fa fa-glass fa-3x" aria-hidden="true"></i></span>
        <span><i class="fa fa-music fa-3x" aria-hidden="true"></i></span>
        <span><i class="fa fa-search fa-3x" aria-hidden="true"></i></span>
        <span><i class="fa fa-envelope-o fa-3x" aria-hidden="true"></i></span>
        <span><i class="fa fa-heart fa-3x" aria-hidden="true"></i></span>
        <span><i class="fa fa-star fa-3x" aria-hidden="true"></i></span>
        <span><i class="fa fa-star-o fa-3x" aria-hidden="true"></i></span>
        <i class="fa fa-user fa-3x" aria-hidden="true"></i>
        <i class="fa fa-film fa-3x" aria-hidden="true"></i>
        <i class="fa fa-th-large fa-3x" aria-hidden="true"></i>
        <i class="fa fa-th fa-3x" aria-hidden="true"></i>
        <i class="fa fa-th-list fa-3x" aria-hidden="true"></i>
        <i class="fa fa-check fa-3x" aria-hidden="true"></i>
        <i class="fa fa-times fa-3x" aria-hidden="true"></i>
        <i class="fa fa-search-minus fa-3x" aria-hidden="true"></i>
        <i class="fa fa-power-off fa-3x" aria-hidden="true"></i>
        <i class="fa fa-signal fa-3x" aria-hidden="true"></i>
        <i class="fa fa-cog fa-3x" aria-hidden="true"></i>
        <i class="fa fa-trash-o fa-3x" aria-hidden="true"></i>
        <i class="fa fa-home fa-3x" aria-hidden="true"></i>
        <i class="fa fa-file-o fa-3x" aria-hidden="true"></i>
        <i class="fa fa-clock-o fa-3x" aria-hidden="true"></i>
        <i class="fa fa-road fa-3x" aria-hidden="true"></i>
    </div>
</div>

jojo_style/templates/jojo_style/partials/style_typography.html
<div class="title">
    <span><i class="fa fa-info" aria-hidden="true"></i></span>
    <h4 style="display:inline-block">TYPOGRAPHY</h4>
</div>
<div class="content">
        For typography, we use our font-company Gotham. But we insert some font style in font-family, embed from google-font.  here are the font-family, Gotham, Monsterrat, Arial.
</div>

<h1>
    H1 Header
</h1>
<div class="font-details">
    Gotham Bold / 36px / Uppercase / line space 42
</div>
<h2>
    H2 Preheader/title
</h2>
<div class="font-details">
    Gotham Bold / 24px / Uppercase / line space 28
</div>
<h3>
    h3 Preheader/title
</h3>
<div class="font-details">
    Gotham Bold / 18px / Uppercase / line space 26
</div>
<h4>
    h4 Preheader/title
</h4>
<div class="font-details">
    Gotham Bold / 14px / Uppercase / line space 20
</div>
<div class="content">
    Content
</div>
<div class="font-details">
    Gotham Book / 12px / line space 18
</div>
<div class="detail-info">
    Label and Detail Information
</div>
<div class="font-details">
    Gotham Book / 10px / line space 18
</div>
<div class="btn-label">
    button attribute
</div>
<div class="font-details">
    Gotham Medium / 14px / Uppercase / line space 20
</div>
<div class="sidebar__content">
    navigation side bar
</div>
<div class="font-details">
    Gotham Book / 11px / Uppercase / line space 20
</div>